import { GradeBand, SubjectInfo, Lesson, Badge, StudyGroup } from '../types';

export const INITIAL_BADGES: Badge[] = [
  {
    id: 'badge-starter',
    name: 'CAPS Pioneer',
    description: 'Completed your first official CAPS lesson on Elevate',
    icon: 'Sparkles',
    unlockedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'badge-quiz-ace',
    name: 'Distinction Whiz',
    description: 'Scored 100% on any subject quiz',
    icon: 'Award',
  },
  {
    id: 'badge-matric-ready',
    name: 'NSC & IEB Ready',
    description: 'Mastered core matric modules with step-by-step exam mastery',
    icon: 'GraduationCap',
  },
  {
    id: 'badge-study-squad',
    name: 'Bantu Collaborator',
    description: 'Joined a study group of fellow South African learners',
    icon: 'Users',
  },
  {
    id: 'badge-note-keeper',
    name: 'Top Notetaker',
    description: 'Saved your personal study notes in the cloud across 3 lessons',
    icon: 'BookOpen',
  },
  {
    id: 'badge-sa-polyglot',
    name: 'Multilingual Scholar',
    description: 'Learned with Ms Elevate across South African national languages',
    icon: 'Globe',
  },
];

export const GRADE_BANDS: { band: GradeBand; label: string; phase: string; grades: string[] }[] = [
  {
    band: 'Grade R-3',
    label: 'Foundation Phase (Grade R - 3)',
    phase: 'Foundation Phase',
    grades: ['Grade R', 'Grade 1', 'Grade 2', 'Grade 3'],
  },
  {
    band: 'Grade 4-6',
    label: 'Intermediate Phase (Grade 4 - 6)',
    phase: 'Intermediate Phase',
    grades: ['Grade 4', 'Grade 5', 'Grade 6'],
  },
  {
    band: 'Grade 7-9',
    label: 'Senior Phase (Grade 7 - 9)',
    phase: 'Senior Phase',
    grades: ['Grade 7', 'Grade 8', 'Grade 9'],
  },
  {
    band: 'Grade 10-12',
    label: 'FET Phase & Matric (Grade 10 - 12)',
    phase: 'FET Phase (NSC & IEB)',
    grades: ['Grade 10', 'Grade 11', 'Grade 12 (Matric)'],
  },
];

export const SUBJECTS: SubjectInfo[] = [
  // Grade R-3
  {
    id: 'r3-hl',
    name: 'Home Language (isiZulu / English)',
    code: 'HL-F',
    iconName: 'BookA',
    gradeBand: 'Grade R-3',
    description: 'Phonics, reading fluency, handwriting, and listening comprehension.',
  },
  {
    id: 'r3-fal',
    name: 'FAL English',
    code: 'FAL-F',
    iconName: 'Languages',
    gradeBand: 'Grade R-3',
    description: 'First Additional Language English vocabulary and sentence building.',
  },
  {
    id: 'r3-math',
    name: 'Mathematics',
    code: 'MATH-F',
    iconName: 'Calculator',
    gradeBand: 'Grade R-3',
    description: 'Numbers, operations, geometric patterns, measurement, and data handling.',
  },
  {
    id: 'r3-life',
    name: 'Life Skills',
    code: 'LS-F',
    iconName: 'HeartHandshake',
    gradeBand: 'Grade R-3',
    description: 'Beginning knowledge, personal and social well-being, creative arts, and physical education.',
  },

  // Grade 4-6
  {
    id: '46-hl',
    name: 'Home Language',
    code: 'HL-I',
    iconName: 'BookA',
    gradeBand: 'Grade 4-6',
    description: 'Reading comprehension, language structures, conventions, and creative writing.',
  },
  {
    id: '46-fal',
    name: 'FAL English',
    code: 'FAL-I',
    iconName: 'Languages',
    gradeBand: 'Grade 4-6',
    description: 'Grammar, summaries, oral presentations, and vocabulary acquisition.',
  },
  {
    id: '46-math',
    name: 'Mathematics',
    code: 'MATH-I',
    iconName: 'Calculator',
    gradeBand: 'Grade 4-6',
    description: 'Fractions, long division, 2D shapes, 3D objects, and word problems.',
  },
  {
    id: '46-nst',
    name: 'Natural Sciences & Technology',
    code: 'NST-I',
    iconName: 'Microscope',
    gradeBand: 'Grade 4-6',
    description: 'Matter and materials, living systems, energy, and structural processing.',
  },
  {
    id: '46-ss',
    name: 'Social Sciences',
    code: 'SS-I',
    iconName: 'Compass',
    gradeBand: 'Grade 4-6',
    description: 'South African history, ancient societies, maps, and climate regions.',
  },
  {
    id: '46-life',
    name: 'Life Skills',
    code: 'LS-I',
    iconName: 'HeartHandshake',
    gradeBand: 'Grade 4-6',
    description: 'Personal safety, nutrition, cultural diversity, and visual arts.',
  },

  // Grade 7-9
  {
    id: '79-hl',
    name: 'Home Language',
    code: 'HL-S',
    iconName: 'BookA',
    gradeBand: 'Grade 7-9',
    description: 'Literature analysis, poetry, critical language awareness, and essay writing.',
  },
  {
    id: '79-fal',
    name: 'FAL English',
    code: 'FAL-S',
    iconName: 'Languages',
    gradeBand: 'Grade 7-9',
    description: 'Sentence synthesis, visual literacy, cartoons, and transactional texts.',
  },
  {
    id: '79-math',
    name: 'Mathematics',
    code: 'MATH-S',
    iconName: 'Calculator',
    gradeBand: 'Grade 7-9',
    description: 'Algebraic expressions, linear equations, geometry of straight lines, and functions.',
  },
  {
    id: '79-ns',
    name: 'Natural Sciences',
    code: 'NS-S',
    iconName: 'Atom',
    gradeBand: 'Grade 7-9',
    description: 'Atomic theory, chemical reactions, photosynthesis, and electric circuits.',
  },
  {
    id: '79-ss',
    name: 'Social Sciences',
    code: 'SS-S',
    iconName: 'Compass',
    gradeBand: 'Grade 7-9',
    description: 'Apartheid history, cold war, topographic maps, and settlement geography.',
  },
  {
    id: '79-tech',
    name: 'Technology',
    code: 'TECH-S',
    iconName: 'Cpu',
    gradeBand: 'Grade 7-9',
    description: 'Mechanical systems, electrical gear ratios, pneumatic hydraulics, and design brief.',
  },
  {
    id: '79-ems',
    name: 'EMS (Economic & Management Sciences)',
    code: 'EMS-S',
    iconName: 'TrendingUp',
    gradeBand: 'Grade 7-9',
    description: 'Accounting equation, CRJ/CPJ journals, the economy, and entrepreneurship.',
  },
  {
    id: '79-lo',
    name: 'Life Orientation',
    code: 'LO-S',
    iconName: 'ShieldCheck',
    gradeBand: 'Grade 7-9',
    description: 'Career choices, study skills, human rights, and emotional health.',
  },
  {
    id: '79-ca',
    name: 'Creative Arts',
    code: 'CA-S',
    iconName: 'Palette',
    gradeBand: 'Grade 7-9',
    description: 'Drama, music, visual arts, and indigenous South African theatre forms.',
  },

  // Grade 10-12
  {
    id: '1012-math',
    name: 'Mathematics',
    code: 'MATH-FET',
    iconName: 'Sigma',
    gradeBand: 'Grade 10-12',
    isHighDemand: true,
    description: 'Paper 1 Algebra & Calculus, Paper 2 Analytical & Euclidean Geometry and Trigonometry.',
  },
  {
    id: '1012-mathlit',
    name: 'Mathematical Literacy',
    code: 'MLIT-FET',
    iconName: 'Calculator',
    gradeBand: 'Grade 10-12',
    description: 'Finance, VAT, personal income tax, measurements, maps, plans, and tariffs.',
  },
  {
    id: '1012-phys',
    name: 'Physical Sciences',
    code: 'PHYS-FET',
    iconName: 'Zap',
    gradeBand: 'Grade 10-12',
    isHighDemand: true,
    description: 'Newtonian mechanics, work-energy, Doppler effect, electrodynamics, organic chemistry.',
  },
  {
    id: '1012-life',
    name: 'Life Sciences',
    code: 'LFSC-FET',
    iconName: 'Dna',
    gradeBand: 'Grade 10-12',
    isHighDemand: true,
    description: 'DNA replication, genetics & inheritance, human nervous system, evolution & hominids.',
  },
  {
    id: '1012-hl',
    name: 'Home Language',
    code: 'HL-FET',
    iconName: 'BookA',
    gradeBand: 'Grade 10-12',
    description: 'Literature (Hamlet / Life of Pi), poetry analysis, critical language Paper 1, essays.',
  },
  {
    id: '1012-fal',
    name: 'FAL English',
    code: 'FAL-FET',
    iconName: 'Languages',
    gradeBand: 'Grade 10-12',
    description: 'Paper 1 language mastery, Paper 2 prescribed novels/dramas, and transactional writing.',
  },
  {
    id: '1012-lo',
    name: 'Life Orientation',
    code: 'LO-FET',
    iconName: 'ShieldCheck',
    gradeBand: 'Grade 10-12',
    description: 'Higher education admissions, bursary planning, stress management, and democracy.',
  },
  {
    id: '1012-geog',
    name: 'Geography',
    code: 'GEOG-FET',
    iconName: 'Globe2',
    gradeBand: 'Grade 10-12',
    description: 'Mid-latitude cyclones, valley climates, geomorphology, rural/urban settlement, and GIS.',
  },
  {
    id: '1012-hist',
    name: 'History',
    code: 'HIST-FET',
    iconName: 'Landmark',
    gradeBand: 'Grade 10-12',
    description: 'Cold War crises, Civil Rights Movement, Black Consciousness, TRC, and essay techniques.',
  },
  {
    id: '1012-bs',
    name: 'Business Studies',
    code: 'BUS-FET',
    iconName: 'Briefcase',
    gradeBand: 'Grade 10-12',
    description: 'Macro business environments, legislation (BEE, BCEA, CPA), CSR, and human resources.',
  },
  {
    id: '1012-acc',
    name: 'Accounting',
    code: 'ACC-FET',
    iconName: 'Receipt',
    gradeBand: 'Grade 10-12',
    description: 'Financial statements for companies, balance sheets, cash flow statements, and ratio analysis.',
  },
  {
    id: '1012-econ',
    name: 'Economics',
    code: 'ECON-FET',
    iconName: 'CircleDollarSign',
    gradeBand: 'Grade 10-12',
    description: 'Circular flow, business cycles, public sector intervention, foreign exchange, inflation.',
  },
  {
    id: '1012-cat',
    name: 'Computer Applications Technology (CAT)',
    code: 'CAT-FET',
    iconName: 'FileSpreadsheet',
    gradeBand: 'Grade 10-12',
    description: 'Advanced Excel formulas (VLOOKUP, IF, NESTED), Access relational databases, and HTML/CSS.',
  },
  {
    id: '1012-it',
    name: 'Information Technology (IT)',
    code: 'IT-FET',
    iconName: 'Terminal',
    gradeBand: 'Grade 10-12',
    description: 'OOP Java/Delphi, 1D & 2D arrays, database SQL integration, algorithms, and theory.',
  },
];

export const LESSONS: Lesson[] = [
  // Grade 10-12 Mathematics - Lesson 1 (Free)
  {
    id: 'les-math-1012-1',
    gradeBand: 'Grade 10-12',
    gradeLevel: 'Grade 12',
    subjectId: '1012-math',
    subjectName: 'Mathematics',
    title: 'Differential Calculus: First Principles & Derivative Shortcuts',
    topic: 'Paper 1 - Calculus & Polynomial Functions',
    order: 1,
    isFree: true,
    durationMinutes: 18,
    capsObjective: 'Demonstrate understanding of the derivative f\'(x) definition from first principles: f\'(x) = lim (h -> 0) [f(x+h) - f(x)] / h, and use standard differentiation rules.',
    summaryNotes: [
      'The derivative of a function f(x) gives the instantaneous rate of change or the gradient of the tangent to the curve at any point (x, f(x)).',
      'First Principles Formula: f\'(x) = lim_{h -> 0} [f(x+h) - f(x)] / h. You MUST retain the lim notation until the h in the denominator is cancelled out.',
      'Power Rule Shortcut: If f(x) = a * x^n, then f\'(x) = n * a * x^(n-1). Constant rule: The derivative of any constant k is 0.',
      'Algebraic Preparation: Before differentiating, rewrite roots as fractional powers (e.g. sqrt(x) = x^(1/2)) and move variables out of denominators (e.g. 3/x^2 = 3 * x^(-2)).',
    ],
    keyTerms: [
      { term: 'Derivative (f\'(x))', definition: 'The gradient function providing the steepness of the tangent line at any x value.' },
      { term: 'First Principles', definition: 'The foundational algebraic limit process establishing the tangent gradient without using shortcut rules.' },
      { term: 'Stationary Point', definition: 'A local turning point or inflection point where the first derivative f\'(x) = 0.' },
    ],
    practicalExample: {
      scenario: 'Determine f\'(x) from first principles given f(x) = 3x^2 - 5x.',
      stepByStepSolution: [
        'Step 1: Write down the CAPS formula: f\'(x) = lim_{h -> 0} [f(x+h) - f(x)] / h.',
        'Step 2: Find f(x+h): f(x+h) = 3(x+h)^2 - 5(x+h) = 3(x^2 + 2xh + h^2) - 5x - 5h = 3x^2 + 6xh + 3h^2 - 5x - 5h.',
        'Step 3: Subtract f(x): f(x+h) - f(x) = (3x^2 + 6xh + 3h^2 - 5x - 5h) - (3x^2 - 5x) = 6xh + 3h^2 - 5h.',
        'Step 4: Factor out h in the numerator: h(6x + 3h - 5) / h.',
        'Step 5: Cancel h (for h ≠ 0) and evaluate limit as h -> 0: lim_{h -> 0} (6x + 3h - 5) = 6x - 5.',
      ],
      examTip: 'DBE Matric Examiners penalize 1 mark if you omit "lim_{h -> 0}" before the final substitution step! Check with the power rule: d/dx(3x^2 - 5x) = 6x - 5 to guarantee your 5 marks.',
    },
    video: {
      title: 'CAPS First Principles Walkthrough - Past NSC Paper Example',
      duration: '7:42',
      thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
    },
    quiz: [
      {
        id: 'q-math-1',
        question: 'What is the derivative of f(x) = 4x^3 - 7x + 9 with respect to x?',
        options: ['12x^2 - 7', '12x^2 - 7x', '4x^2 - 7', '12x^3 - 7'],
        correctIndex: 0,
        explanation: 'Applying the power rule: d/dx(4x^3) = 12x^2, d/dx(-7x) = -7, and d/dx(9) = 0. Therefore, f\'(x) = 12x^2 - 7.',
      },
      {
        id: 'q-math-2',
        question: 'Before taking the derivative of g(x) = 2 / x^3, how should the term be algebraically rewritten?',
        options: ['2 * x^(-3)', '2 * x^3', 'x^(-3) / 2', '(2/x)^3'],
        correctIndex: 0,
        explanation: 'Move x^3 from denominator to numerator by applying the exponent law 1/x^n = x^(-n), yielding 2 * x^(-3).',
      },
      {
        id: 'q-math-3',
        question: 'If f\'(a) = 0 for a cubic polynomial, what does this indicate geometrically about the point on the curve?',
        options: ['The tangent is horizontal (stationary/turning point)', 'The curve crosses the x-axis', 'The gradient is undefined', 'The graph has a vertical asymptote'],
        correctIndex: 0,
        explanation: 'When the derivative f\'(x) equals 0, the gradient of the tangent line is zero, which corresponds to a horizontal tangent at a stationary point.',
      },
      {
        id: 'q-math-4',
        question: 'In the first principles definition, what happens when h = 0 is substituted prematurely into [f(x+h) - f(x)] / h?',
        options: ['An indeterminate 0/0 error occurs', 'The answer is always 0', 'The function becomes continuous', 'The gradient equals f(x)'],
        correctIndex: 0,
        explanation: 'Direct substitution yields 0 in the denominator, resulting in division by zero. You must first factor out and cancel h.',
      },
      {
        id: 'q-math-5',
        question: 'Find the gradient of the tangent to y = x^2 - 3x at the point where x = 4.',
        options: ['5', '4', '8', '1'],
        correctIndex: 0,
        explanation: 'The derivative is dy/dx = 2x - 3. Substituting x = 4 gives: 2(4) - 3 = 8 - 3 = 5.',
      },
    ],
  },

  // Grade 10-12 Mathematics - Lesson 2 (Free)
  {
    id: 'les-math-1012-2',
    gradeBand: 'Grade 10-12',
    gradeLevel: 'Grade 12',
    subjectId: '1012-math',
    subjectName: 'Mathematics',
    title: 'Financial Mathematics: Annuities & Sinking Funds',
    topic: 'Paper 1 - Future & Present Value Annuities',
    order: 2,
    isFree: true,
    durationMinutes: 20,
    capsObjective: 'Solve compound interest problems involving regular payments into future value funds, bond repayments via present value annuities, and sinking fund replacement calculations.',
    summaryNotes: [
      'Future Value Annuity: F = x * [((1 + i)^n - 1) / i]. Used when saving money regularly towards a future target (investments, retirement).',
      'Present Value Annuity: P = x * [(1 - (1 + i)^(-n)) / i]. Used when repaying a loan or home bond borrowed today.',
      'Interest Rate Conversion: i is always the nominal rate divided by the compounding frequency (e.g. 12% p.a. compounded monthly -> i = 0.12 / 12 = 0.01).',
      'Number of Payments (n): For monthly payments over 20 years, n = 20 * 12 = 240 payments.',
    ],
    keyTerms: [
      { term: 'Sinking Fund', definition: 'A savings fund established by a business to replace depreciating capital machinery in the future.' },
      { term: 'Deferred Annuity', definition: 'A loan repayment schedule that begins only after an initial grace period.' },
    ],
    practicalExample: {
      scenario: 'Sipho secures a home loan of R850,000 at 10.5% p.a. compounded monthly over 20 years. Calculate his monthly bond instalment.',
      stepByStepSolution: [
        'Step 1: Identify variables: P = 850,000, i = 0.105 / 12 = 0.00875, n = 20 * 12 = 240 months.',
        'Step 2: Formula: P = x * [1 - (1 + i)^(-n)] / i.',
        'Step 3: Rearrange for monthly payment x: x = (P * i) / [1 - (1 + i)^(-n)].',
        'Step 4: Substitute: x = (850,000 * 0.00875) / [1 - (1.00875)^(-240)] = 7,437.50 / [1 - 0.12396] = 7,437.50 / 0.87604.',
        'Step 5: x ≈ R8,489.91 per month.',
      ],
      examTip: 'Remember to always round your final monetary answer to 2 decimal places (cents), never round intermediate calculator steps!',
    },
    video: {
      title: 'Matric Financial Maths: Present vs Future Value Annuities Masterclass',
      duration: '9:15',
      thumbnailUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
    },
    quiz: [
      {
        id: 'q-fin-1',
        question: 'Which formula must be used to calculate monthly repayments for a vehicle financing loan taken today?',
        options: ['Present Value Annuity (P)', 'Future Value Annuity (F)', 'Simple Interest (A = P(1+in))', 'Compound Decay'],
        correctIndex: 0,
        explanation: 'Loans, bonds, and mortgages involve receiving capital today and paying it back, requiring the Present Value annuity formula.',
      },
      {
        id: 'q-fin-2',
        question: 'If an interest rate is quoted as 9% p.a. compounded quarterly, what value of i should be used in the annuity formula?',
        options: ['0.0225', '0.09', '0.0075', '0.03'],
        correctIndex: 0,
        explanation: 'Quarterly means 4 times a year: 0.09 / 4 = 0.0225.',
      },
      {
        id: 'q-fin-3',
        question: 'When calculating a sinking fund, how is the required future replacement cost calculated?',
        options: ['By inflating the current purchase price using compound interest', 'By reducing the scrap value to zero', 'By dividing by 12', 'By taking the simple interest only'],
        correctIndex: 0,
        explanation: 'Machinery replacement requires inflating the cost of new equipment over time using A = P(1 + i)^n, then subtracting scrap value.',
      },
      {
        id: 'q-fin-4',
        question: 'What happens to the total interest paid on a 20-year bond if the borrower pays an extra R500 every month?',
        options: ['Total interest decreases significantly and term shortens', 'Total interest remains identical', 'Total interest increases', 'The bank charges penalties exceeding interest'],
        correctIndex: 0,
        explanation: 'Additional capital payments reduce the outstanding principal balance quicker, cutting compound interest and loan duration.',
      },
      {
        id: 'q-fin-5',
        question: 'What is the value of n for an investment paid monthly over 5 years where the first deposit is made immediately?',
        options: ['61 payments (n = 60 + 1)', '60 payments', '50 payments', '12 payments'],
        correctIndex: 0,
        explanation: 'An immediate payment on day 0 means one additional compounding payment occurs: 5 * 12 + 1 = 61 payments.',
      },
    ],
  },

  // Grade 10-12 Mathematics - Lesson 3 (Free)
  {
    id: 'les-math-1012-3',
    gradeBand: 'Grade 10-12',
    gradeLevel: 'Grade 12',
    subjectId: '1012-math',
    subjectName: 'Mathematics',
    title: 'Euclidean Geometry: Proportionality & Similarity Theorems',
    topic: 'Paper 2 - Circle Geometry & Triangle Ratios',
    order: 3,
    isFree: true,
    durationMinutes: 22,
    capsObjective: 'Apply the Proportional Intercept Theorem and Triangle Similarity conditions (equiangular) to prove geometric ratios and calculate unknown lengths.',
    summaryNotes: [
      'Proportionality Theorem: A line drawn parallel to one side of a triangle divides the other two sides proportionally (Reason: line || one side of ∆).',
      'Similarity Theorem: If two triangles are equiangular, their corresponding sides are in the same proportion (Reason: ||| ∆s or equiangular ∆s).',
      'Area Ratio Property: The ratio of the areas of two triangles with equal altitudes is equal to the ratio of their bases.',
      'Exam writing standard: Every geometric assertion MUST be accompanied by its accepted DBE CAPS code reason.',
    ],
    keyTerms: [
      { term: 'Equiangular Triangles', definition: 'Two triangles whose three interior angles are pair-wise congruent.' },
      { term: 'Similarity Ratio', definition: 'The constant factor relating lengths of corresponding sides: AB/DE = BC/EF = AC/DF.' },
    ],
    practicalExample: {
      scenario: 'In ∆ABC, line DE is drawn parallel to BC with D on AB and E on AC. If AD = 6 cm, DB = 9 cm, and AE = 4 cm, calculate the length of EC.',
      stepByStepSolution: [
        'Step 1: State the parallel line relationship: DE || BC (Given).',
        'Step 2: Apply the Proportionality Theorem: AD / DB = AE / EC [Reason: line || one side of ∆].',
        'Step 3: Substitute the known values: 6 / 9 = 4 / EC.',
        'Step 4: Cross multiply: 6 * EC = 9 * 4 = 36.',
        'Step 5: Solve for EC: EC = 36 / 6 = 6 cm.',
      ],
      examTip: 'Never forget to write the CAPS theorem reason in square brackets next to your step; examiners deduct 1 mark per missing reason in Paper 2!',
    },
    video: {
      title: 'Paper 2 Euclidean Geometry: Similarity Proofs Made Simple',
      duration: '8:50',
      thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
    },
    quiz: [
      {
        id: 'q-euc-1',
        question: 'What is the required reason in CAPS for stating AD/DB = AE/EC when DE is parallel to BC?',
        options: ['line || one side of ∆', 'tan chord theorem', 'midpoint theorem', 'opposite angles of cyclic quad'],
        correctIndex: 0,
        explanation: 'The DBE approved abbreviation for the proportionality theorem is "line || one side of ∆".',
      },
      {
        id: 'q-euc-2',
        question: 'Two triangles ∆ABC and ∆PQR have angles A=P, B=Q, and C=R. Which conclusion is correct?',
        options: ['∆ABC ||| ∆PQR (equiangular ∆s)', '∆ABC ≡ ∆PQR (congruent)', 'AB = PQ always', 'Area of ∆ABC = Area of ∆PQR'],
        correctIndex: 0,
        explanation: 'Equiangular triangles are similar (|||), meaning corresponding sides are in proportion, but not necessarily equal in size.',
      },
      {
        id: 'q-euc-3',
        question: 'If the linear ratio of two similar triangles is 1:3, what is the ratio of their respective areas?',
        options: ['1:9', '1:3', '1:6', '1:27'],
        correctIndex: 0,
        explanation: 'The ratio of the areas of similar figures is the square of the linear scale ratio: (1/3)^2 = 1/9.',
      },
      {
        id: 'q-euc-4',
        question: 'What is the tangent-chord theorem statement used extensively in circle geometry?',
        options: ['Angle between tangent and chord equals angle subtended in alternate segment', 'Tangent is perpendicular to chord', 'Tangent bisects chord', 'Angles subtended on same arc are equal'],
        correctIndex: 0,
        explanation: 'The angle between a tangent to a circle and a chord drawn through the point of contact equals the angle in the alternate segment.',
      },
      {
        id: 'q-euc-5',
        question: 'In ∆PQR, S is on PQ and T is on PR such that PS/SQ = 2/3. If PT = 8, what is TR if ST || QR?',
        options: ['12', '16', '10', '6'],
        correctIndex: 0,
        explanation: 'By proportionality theorem: PS/SQ = PT/TR => 2/3 = 8/TR => 2*TR = 24 => TR = 12.',
      },
    ],
  },

  // Grade 10-12 Mathematics - Lesson 4 (PREMIUM - BLURRED)
  {
    id: 'les-math-1012-4',
    gradeBand: 'Grade 10-12',
    gradeLevel: 'Grade 12',
    subjectId: '1012-math',
    subjectName: 'Mathematics',
    title: 'Analytical Geometry: Circles with Centers not at Origin & Tangents',
    topic: 'Paper 2 - Circle Equations & Perpendicular Tangent Gradients',
    order: 4,
    isFree: false, // Premium
    durationMinutes: 25,
    capsObjective: 'Determine circle equations of the form (x-a)^2 + (y-b)^2 = r^2 by completing the square and find gradients of tangents using the radius-tangent perpendicular property.',
    summaryNotes: [
      'Standard circle equation: (x - a)^2 + (y - b)^2 = r^2, where center is (a, b) and radius is r.',
      'A radius is perpendicular to the tangent at the point of contact: m_radius * m_tangent = -1.',
      'Completing the square allows converting general form x^2 + y^2 + Dx + Ey + F = 0 into center-radius form.',
    ],
    keyTerms: [
      { term: 'Radius-Tangent Theorem', definition: 'm_tangent = -1 / m_radius at the contact point.' },
    ],
    practicalExample: {
      scenario: 'Find the equation of the tangent to the circle x^2 + y^2 = 25 at the point (3, 4).',
      stepByStepSolution: [
        'Center is (0, 0). Point on circle is (3, 4).',
        'Gradient of radius: m_rad = (4 - 0)/(3 - 0) = 4/3.',
        'Gradient of tangent: m_tan = -3/4 (radius ⊥ tangent).',
        'Tangent equation: y - 4 = -3/4(x - 3) => y = -3/4x + 25/4.',
      ],
      examTip: 'Always verify that the point of contact satisfies the circle equation first!',
    },
    video: {
      title: 'Circle Tangents in Analytical Geometry (Premium Unlock)',
      duration: '11:20',
      thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
      videoUrl: '',
    },
    quiz: [],
  },

  // Grade 10-12 Physical Sciences - Lesson 1 (Free)
  {
    id: 'les-phys-1012-1',
    gradeBand: 'Grade 10-12',
    gradeLevel: 'Grade 12',
    subjectId: '1012-phys',
    subjectName: 'Physical Sciences',
    title: 'Newtonian Mechanics: Newton’s 2nd Law & Connected Bodies',
    topic: 'Physics Paper 1 - Dynamics & Free-Body Diagrams',
    order: 1,
    isFree: true,
    durationMinutes: 20,
    capsObjective: 'State Newton’s 2nd law of motion in words: when a net force acts on an object, it accelerates in the direction of the net force with acceleration directly proportional to the net force and inversely proportional to mass.',
    summaryNotes: [
      'Newton\'s 2nd Law: F_net = m * a. Both F_net and a are vector quantities and must have consistent direction signs (+ and -).',
      'Free-Body Diagrams (FBD): Draw the object as a single dot with labeled arrows pointing away from the dot for each external force (Gravity Fg, Normal force N, Tension T, Friction f).',
      'Frictional force: Kinetic friction f_k = μ_k * N, where N is the perpendicular normal force.',
      'Connected systems (two masses joined by a light inextensible string): Set up two separate F_net = ma equations and solve simultaneously for acceleration and tension.',
    ],
    keyTerms: [
      { term: 'Free-Body Diagram', definition: 'A diagram showing only forces acting directly on a specified object with arrows directed away from the center.' },
      { term: 'Kinetic Friction', definition: 'The opposing force acting parallel to the contact surface on a moving body: f_k = μ_k * N.' },
    ],
    practicalExample: {
      scenario: 'A 5 kg block on a rough horizontal table (μ_k = 0.2) is pulled by a horizontal force of 30 N. Calculate the acceleration of the block.',
      stepByStepSolution: [
        'Step 1: Calculate normal force N: Vertical balance gives N = Fg = m * g = 5 * 9.8 = 49 N.',
        'Step 2: Calculate kinetic friction: f_k = μ_k * N = 0.2 * 49 = 9.8 N to the left.',
        'Step 3: Set up F_net equation: F_applied - f_k = m * a.',
        'Step 4: Substitute: 30 - 9.8 = 5 * a => 20.2 = 5 * a.',
        'Step 5: Solve for a: a = 20.2 / 5 = 4.04 m·s⁻² to the right.',
      ],
      examTip: 'In DBE NSC Physics exams, always state: "Take right as positive" before writing equations. Mark the units (m·s⁻²) clearly!',
    },
    video: {
      title: 'Newton\'s 2nd Law on Inclines & Connected Blocks - NSC Paper Walkthrough',
      duration: '10:14',
      thumbnailUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&auto=format&fit=crop&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
    },
    quiz: [
      {
        id: 'q-phys-1',
        question: 'Which is the correct CAPS definition of Newton\'s Second Law of Motion?',
        options: [
          'When a net force acts on an object, it accelerates in the direction of the net force with acceleration proportional to net force and inversely proportional to mass',
          'Every action has an equal and opposite reaction',
          'An object continues at rest or constant velocity unless acted upon by a non-zero net force',
          'Force equals mass divided by acceleration',
        ],
        correctIndex: 0,
        explanation: 'DBE requires the exact proportional wording: acceleration is directly proportional to net force and inversely proportional to mass.',
      },
      {
        id: 'q-phys-2',
        question: 'What is the normal force acting on a 10 kg crate resting on a horizontal floor when no vertical external forces are applied? (g = 9.8 m·s⁻²)',
        options: ['98 N upwards', '10 N upwards', '0 N', '980 N downwards'],
        correctIndex: 0,
        explanation: 'Since there is no vertical acceleration, N = m * g = 10 * 9.8 = 98 N acting upwards.',
      },
      {
        id: 'q-phys-3',
        question: 'In a free-body diagram representing a crate pulled up a rough inclined plane, which force acts parallel down the slope?',
        options: ['Component of gravity (Fg_parallel) and kinetic friction (fk)', 'Normal force', 'Applied tension', 'Component of gravity perpendicular (Fg_perp)'],
        correctIndex: 0,
        explanation: 'Both the parallel component of gravity (m*g*sinθ) and kinetic friction oppose upward motion along the incline.',
      },
      {
        id: 'q-phys-4',
        question: 'What happens to the acceleration of an object if the net force acting on it is doubled while its mass is quadrupled?',
        options: ['Acceleration is halved (0.5a)', 'Acceleration is doubled', 'Acceleration remains unchanged', 'Acceleration is quadrupled'],
        correctIndex: 0,
        explanation: 'a = F_net / m. If F_net -> 2F and m -> 4m, then a_new = 2/4 * (F/m) = 0.5 a.',
      },
      {
        id: 'q-phys-5',
        question: 'What is the correct unit of kinetic frictional force in the SI system?',
        options: ['Newton (N)', 'Joule (J)', 'Watt (W)', 'kg·m·s⁻¹'],
        correctIndex: 0,
        explanation: 'Frictional force is a force, measured in Newtons (N).',
      },
    ],
  },

  // Grade 10-12 Life Sciences - Lesson 1 (Free)
  {
    id: 'les-life-1012-1',
    gradeBand: 'Grade 10-12',
    gradeLevel: 'Grade 12',
    subjectId: '1012-life',
    subjectName: 'Life Sciences',
    title: 'Genetics & Inheritance: Mendel’s Laws & Dihybrid Crosses',
    topic: 'Paper 2 - Genetics, DNA & Meiosis',
    order: 1,
    isFree: true,
    durationMinutes: 19,
    capsObjective: 'Understand Mendel’s Law of Segregation and Law of Independent Assortment, perform genetic crosses using Punnett squares, and predict phenotypic and genotypic ratios.',
    summaryNotes: [
      'Gene: A segment of DNA coding for a specific functional protein or characteristic.',
      'Alleles: Alternative forms of the same gene located at the same locus on homologous chromosomes.',
      'Mendel\'s Law of Segregation: Characteristics are controlled by pairs of alleles that separate during gamete formation in meiosis.',
      'Monohybrid standard phenotypic ratio for two heterozygous parents (Tt x Tt): 3 dominant : 1 recessive (75% to 25%).',
      'Format in NSC Paper 2: State P1 phenotype, P1 genotype, Meiosis/Gametes, Fertilization, F1 genotype, and F1 phenotype.',
    ],
    keyTerms: [
      { term: 'Homozygous', definition: 'Having two identical alleles for a particular gene (e.g. BB or bb).' },
      { term: 'Heterozygous', definition: 'Having two different alleles for a particular gene (e.g. Bb).' },
      { term: 'Phenotype', definition: 'The physical observable characteristic of an organism.' },
    ],
    practicalExample: {
      scenario: 'In humans, brown eye color (B) is dominant over blue eye color (b). A heterozygous brown-eyed male marries a blue-eyed female. Determine the phenotypic probability of their offspring having blue eyes.',
      stepByStepSolution: [
        'Step 1: P1 Phenotypes: Brown eyes x Blue eyes.',
        'Step 2: P1 Genotypes: Bb x bb.',
        'Step 3: Meiosis -> Gametes: B and b (from father), b and b (from mother).',
        'Step 4: Punnett square fertilization combinations: Bb, Bb, bb, bb.',
        'Step 5: F1 Genotypes: 2 Bb : 2 bb (50% heterozygous, 50% homozygous recessive).',
        'Step 6: F1 Phenotypes: 2 Brown eyes : 2 Blue eyes (50% brown, 50% blue). Probability of blue eyes is 50% or 0.5.',
      ],
      examTip: 'Life Sciences examiners require the formal 6-line genetic cross format! Always write the words "Meiosis" and "Fertilization" between gametes and offspring to earn full 6 marks.',
    },
    video: {
      title: 'Mendelian Genetics & Pedigree Diagrams - CAPS Matric Life Sciences',
      duration: '8:30',
      thumbnailUrl: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=600&auto=format&fit=crop&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
    },
    quiz: [
      {
        id: 'q-gen-1',
        question: 'What is the expected phenotypic ratio in the offspring of two heterozygous individuals in complete dominance?',
        options: ['3 : 1', '1 : 2 : 1', '9 : 3 : 3 : 1', '1 : 1'],
        correctIndex: 0,
        explanation: 'A heterozygous cross (e.g. Tt x Tt) produces 1 TT : 2 Tt : 1 tt, which expresses as 3 dominant phenotypes to 1 recessive phenotype.',
      },
      {
        id: 'q-gen-2',
        question: 'Which process in Meiosis I ensures that maternal and paternal chromosomes sort independently into gametes?',
        options: ['Random assortment of homologous chromosomes at metaphase I', 'DNA replication in interphase', 'Cytokinesis', 'Spindle fiber degeneration'],
        correctIndex: 0,
        explanation: 'Random arrangement of homologous chromosomes at the equator during metaphase I generates independent assortment.',
      },
      {
        id: 'q-gen-3',
        question: 'If a plant with red flowers (RR) is crossed with a plant with white flowers (WW) and all offspring have pink flowers (RW), what type of inheritance is demonstrated?',
        options: ['Incomplete dominance', 'Complete dominance', 'Co-dominance', 'Polygenic inheritance'],
        correctIndex: 0,
        explanation: 'Incomplete dominance results in an intermediate blending of the two parental phenotypes, such as pink flowers from red and white.',
      },
      {
        id: 'q-gen-4',
        question: 'What term describes an individual carrying two different alleles at a given gene locus?',
        options: ['Heterozygous', 'Homozygous', 'Hemizygous', 'Phenotypic'],
        correctIndex: 0,
        explanation: 'Heterozygous means having two different alleles (e.g. Aa).',
      },
      {
        id: 'q-gen-5',
        question: 'How many chromosomes are present in a normal human gamete (sperm or ovum)?',
        options: ['23 (haploid)', '46 (diploid)', '44 (autosomes only)', '2'],
        correctIndex: 0,
        explanation: 'Human gametes are haploid (n = 23), half of the somatic cell count (2n = 46).',
      },
    ],
  },

  // Grade 7-9 EMS (Economic & Management Sciences) - Lesson 1 (Free)
  {
    id: 'les-ems-79-1',
    gradeBand: 'Grade 7-9',
    gradeLevel: 'Grade 9',
    subjectId: '79-ems',
    subjectName: 'EMS',
    title: 'The Accounting Equation: Assets = Owners’ Equity + Liabilities',
    topic: 'Financial Literacy - Business Transactions & Accounting Equation',
    order: 1,
    isFree: true,
    durationMinutes: 16,
    capsObjective: 'Analyze business transactions according to the fundamental accounting equation: Assets (A) = Owner’s Equity (OE) + Liabilities (L).',
    summaryNotes: [
      'The golden rule of South African double-entry accounting: Assets = Owner\'s Equity + Liabilities.',
      'Assets (A): Possessions owned by the business that bring future economic value (Bank, Equipment, Vehicles, Debtors).',
      'Owner\'s Equity (OE): The owner\'s claim on business assets (Capital +, Drawings -, Income +, Expenses -).',
      'Liabilities (L): Debts owed by the business to outside third parties (Creditors, Bank Loan).',
    ],
    keyTerms: [
      { term: 'Cash Receipts Journal (CRJ)', definition: 'Subsidiary journal recording all cash inflows received by the business.' },
      { term: 'Cash Payments Journal (CPJ)', definition: 'Subsidiary journal recording all payments made by cash, cheque, or electronic funds transfer (EFT).' },
    ],
    practicalExample: {
      scenario: 'The owner deposits R50,000 cash directly into the business bank account as capital contribution. Analyze the effect on the accounting equation.',
      stepByStepSolution: [
        'Step 1: Identify the two accounts involved: Bank (Asset) and Capital (Owner\'s Equity).',
        'Step 2: Bank account increases by R50,000 -> Assets: +50,000.',
        'Step 3: Owner\'s capital contribution increases -> Owner\'s Equity: +50,000.',
        'Step 4: Liabilities remain unaffected -> Liabilities: 0.',
        'Step 5: Check balance: +50,000 (A) = +50,000 (OE) + 0 (L). Both sides balance.',
      ],
      examTip: 'Whenever cash is paid out, Bank (Asset) decreases with a minus sign (-). If paid for an expense like rent, OE decreases (-)!',
    },
    video: {
      title: 'Senior Phase EMS: Master the Accounting Equation Table',
      duration: '6:45',
      thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
    },
    quiz: [
      {
        id: 'q-ems-1',
        question: 'Which formula correctly expresses the basic South African accounting equation?',
        options: ['Assets = Owner’s Equity + Liabilities', 'Liabilities = Assets + Owner’s Equity', 'Owner’s Equity = Assets + Liabilities', 'Assets + Liabilities = Capital'],
        correctIndex: 0,
        explanation: 'Assets = Owner\'s Equity + Liabilities (A = OE + L).',
      },
      {
        id: 'q-ems-2',
        question: 'When a business purchases merchandise inventory on credit from a supplier, which two accounts are affected?',
        options: ['Trading Stock (Asset +) and Creditors Control (Liability +)', 'Bank (Asset -) and Capital (OE +)', 'Cost of Sales (OE -) and Bank (Asset -)', 'Debtors Control (Asset +) and Sales (OE +)'],
        correctIndex: 0,
        explanation: 'Goods increase stock (Asset +) and debt to the supplier increases liabilities (Creditors Control +).',
      },
      {
        id: 'q-ems-3',
        question: 'What is the impact of paying monthly business electricity of R2,500 via EFT on the accounting equation?',
        options: ['Assets -2,500 (Bank) and OE -2,500 (Electricity expense)', 'Assets +2,500 and Liabilities +2,500', 'OE +2,500 and Liabilities -2,500', 'No change to Assets'],
        correctIndex: 0,
        explanation: 'Bank decreases (-Asset) and electricity is an expense which decreases Owner\'s Equity (-OE).',
      },
      {
        id: 'q-ems-4',
        question: 'In which journal are cash sales of merchandise recorded?',
        options: ['Cash Receipts Journal (CRJ)', 'Cash Payments Journal (CPJ)', 'General Journal (GJ)', 'Debtors Journal (DJ)'],
        correctIndex: 0,
        explanation: 'Money received by cash or card is logged in the Cash Receipts Journal.',
      },
      {
        id: 'q-ems-5',
        question: 'What is "Drawings" in EMS accounting terms?',
        options: ['Money or inventory taken from the business by the owner for personal use', 'Artistic diagrams made for marketing', 'Interest paid on a bank loan', 'Money owed by customers'],
        correctIndex: 0,
        explanation: 'Drawings represent assets withdrawn by the owner for private usage, reducing Owner\'s Equity.',
      },
    ],
  },

  // Grade 4-6 Natural Sciences & Technology - Lesson 1 (Free)
  {
    id: 'les-nst-46-1',
    gradeBand: 'Grade 4-6',
    gradeLevel: 'Grade 6',
    subjectId: '46-nst',
    subjectName: 'Natural Sciences & Technology',
    title: 'Photosynthesis & Ecosystem Food Webs in South Africa',
    topic: 'Life and Living - Ecosystem Energy Flow',
    order: 1,
    isFree: true,
    durationMinutes: 15,
    capsObjective: 'Explain that green plants use sunlight, carbon dioxide from air, and water from soil to produce glucose sugar and oxygen through photosynthesis.',
    summaryNotes: [
      'Photosynthesis word equation: Carbon Dioxide + Water + Sunlight -> Glucose (Food) + Oxygen.',
      'Chlorophyll is the green pigment in plant leaves that traps radiant solar energy.',
      'Plants are PRODUCERS because they manufacture their own food.',
      'South African grasslands and savannah food chains: Acacia tree (Producer) -> Impala (Herbivore) -> Leopard (Carnivore).',
    ],
    keyTerms: [
      { term: 'Producer', definition: 'An organism that produces its own organic nutrients using sunlight (green plants).' },
      { term: 'Herbivore', definition: 'A primary consumer that eats only plants.' },
    ],
    practicalExample: {
      scenario: 'Look at a Kruger National Park ecosystem: Grass -> Zebra -> Lion. Explain what would happen to lions if severe drought dried out the grass.',
      stepByStepSolution: [
        'Step 1: Grass is the primary producer supplying solar energy to the ecosystem.',
        'Step 2: Without grass, zebras have no food source and their population drops.',
        'Step 3: Because lions depend on zebras for prey, the lion population will also starve or migrate.',
      ],
      examTip: 'Food chain arrows ALWAYS point in the direction of energy transfer (from the food into the eater’s mouth)!',
    },
    video: {
      title: 'Ecosystems & Food Webs of Southern Africa',
      duration: '5:50',
      thumbnailUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&auto=format&fit=crop&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
    },
    quiz: [
      {
        id: 'q-nst-1',
        question: 'Which gas is absorbed by green plant leaves from the atmosphere during photosynthesis?',
        options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Helium'],
        correctIndex: 0,
        explanation: 'Green plants absorb carbon dioxide (CO2) from the air through microscopic pores called stomata.',
      },
      {
        id: 'q-nst-2',
        question: 'What is the green pigment found in plant cells that traps sunlight energy?',
        options: ['Chlorophyll', 'Melanin', 'Hemoglobin', 'Glucose'],
        correctIndex: 0,
        explanation: 'Chlorophyll is the green chemical compound in chloroplasts that absorbs sunlight.',
      },
      {
        id: 'q-nst-3',
        question: 'In an ecosystem food chain, what do the directional arrows represent?',
        options: ['The flow of energy from one organism to another', 'Which animal runs faster', 'The age of the animals', 'Water flow'],
        correctIndex: 0,
        explanation: 'Arrows point from the organism being eaten to the consumer that eats it, illustrating energy transfer.',
      },
      {
        id: 'q-nst-4',
        question: 'Which of the following animals is classified as an apex carnivore in South African wildlife?',
        options: ['Lion', 'Zebra', 'Giraffe', 'Impala'],
        correctIndex: 0,
        explanation: 'Lions are top carnivores that hunt herbivores like zebras and impalas.',
      },
      {
        id: 'q-nst-5',
        question: 'What essential gas is released into the atmosphere as a byproduct of plant photosynthesis?',
        options: ['Oxygen', 'Carbon monoxide', 'Methane', 'Ozone'],
        correctIndex: 0,
        explanation: 'Photosynthesis releases oxygen (O2) into the atmosphere, which animals need for cellular respiration.',
      },
    ],
  },

  // Grade R-3 Mathematics - Lesson 1 (Free)
  {
    id: 'les-math-r3-1',
    gradeBand: 'Grade R-3',
    gradeLevel: 'Grade 2',
    subjectId: 'r3-math',
    subjectName: 'Mathematics',
    title: 'Numbers, Operations & Place Value: Tens & Units',
    topic: 'Foundation Phase - Counting & Mental Math',
    order: 1,
    isFree: true,
    durationMinutes: 12,
    capsObjective: 'Decompose 2-digit numbers into multiples of tens and units (e.g. 47 = 40 + 7) and perform mental addition within 100.',
    summaryNotes: [
      'In a 2-digit number, the digit on the left tells how many bundles of TEN we have.',
      'The digit on the right tells how many loose ONES (Units) we have.',
      'Example: 35 has 3 Tens (30) and 5 Units (5).',
      'Breaking down numbers makes adding easy: 24 + 35 = (20 + 30) + (4 + 5) = 50 + 9 = 59.',
    ],
    keyTerms: [
      { term: 'Tens (T)', definition: 'Bundles of ten items grouped together.' },
      { term: 'Units (U)', definition: 'Single loose items from 0 to 9.' },
    ],
    practicalExample: {
      scenario: 'Thandi has 28 marbles. Her brother gives her 14 more marbles. How many marbles does Thandi have in total?',
      stepByStepSolution: [
        'Step 1: Break down 28 into 20 + 8.',
        'Step 2: Break down 14 into 10 + 4.',
        'Step 3: Add the tens: 20 + 10 = 30.',
        'Step 4: Add the units: 8 + 4 = 12.',
        'Step 5: Put it all together: 30 + 12 = 42 marbles.',
      ],
      examTip: 'Count in 10s on your hundred chart: 10, 20, 30, 40, 50!',
    },
    video: {
      title: 'Fun with Tens and Units: South African Classroom Counting',
      duration: '4:15',
      thumbnailUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
    },
    quiz: [
      {
        id: 'q-r3-1',
        question: 'How many Tens are in the number 54?',
        options: ['5 Tens (value 50)', '4 Tens', '54 Tens', '0 Tens'],
        correctIndex: 0,
        explanation: 'In 54, the digit 5 is in the tens place, representing 5 tens (50).',
      },
      {
        id: 'q-r3-2',
        question: 'What is 30 + 7?',
        options: ['37', '307', '10', '73'],
        correctIndex: 0,
        explanation: '30 + 7 = 37.',
      },
      {
        id: 'q-r3-3',
        question: 'If you have 6 bundles of 10 pencils and 3 loose pencils, how many pencils do you have altogether?',
        options: ['63', '36', '9', '60'],
        correctIndex: 0,
        explanation: '6 tens (60) + 3 units (3) = 63 pencils.',
      },
      {
        id: 'q-r3-4',
        question: 'What number comes directly after 79 when counting forwards in ones?',
        options: ['80', '78', '89', '70'],
        correctIndex: 0,
        explanation: '79 + 1 = 80.',
      },
      {
        id: 'q-r3-5',
        question: 'Double 15 is equal to:',
        options: ['30', '25', '20', '35'],
        correctIndex: 0,
        explanation: '15 + 15 = 30.',
      },
    ],
  },
  {
    id: 'les-hl-r3-phonics',
    gradeBand: 'Grade R-3',
    gradeLevel: 'Grade 1',
    subjectId: 'r3-hl',
    subjectName: 'Home Language (isiZulu / English)',
    title: 'Phonics, Letter Sounds & Interactive Voice Reading',
    topic: 'Foundation Phase - Letter Sounds & Word Blending',
    order: 1,
    isFree: true,
    durationMinutes: 10,
    capsObjective: 'Identify single letter sounds (s, a, t, p, i, n) and blend sounds to read simple 3-letter CVC words (cat, sun, mat) and short sentences.',
    summaryNotes: [
      'Every letter in the alphabet has a name and a sound.',
      'Sound out the letter: /s/ as in sun, /a/ as in ant, /t/ as in tap.',
      'Blending is putting sounds together smoothly: c + a + t = cat.',
      'Read from left to right, following each word with your pointer finger.',
    ],
    keyTerms: [
      { term: 'Phonics', definition: 'The link between spoken sounds and the printed letters that represent them.' },
      { term: 'Blending', definition: 'Pushing letter sounds together to pronounce a full word.' },
      { term: 'CVC Word', definition: 'A three-letter word made of Consonant-Vowel-Consonant (like dog, sun, pig).' },
    ],
    practicalExample: {
      scenario: 'How do you sound out the word "cat" and read the sentence: "I see a big cat"?',
      stepByStepSolution: [
        'Step 1: Point to the first letter "c" and make the sound /k/.',
        'Step 2: Point to the middle letter "a" and make the sound /æ/.',
        'Step 3: Point to the last letter "t" and make the sound /t/.',
        'Step 4: Blend them fast: /k/ - /æ/ - /t/ -> "cat"!',
        'Step 5: Read the whole sentence smoothly: "I see a big cat."',
      ],
      examTip: 'Take a deep breath, point to each word, and speak clearly when reading aloud to Ms Elevate!',
    },
    video: {
      title: 'South African Foundation Phase Phonics: Jolly Phonics Sounds',
      duration: '3:50',
      thumbnailUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
    },
    quiz: [
      {
        id: 'q-hl-1',
        question: 'What sound does the letter "s" make?',
        options: ['/s/ like a hissing snake', '/b/ like a ball', '/m/ like yummy food', '/t/ like a clock'],
        correctIndex: 0,
        explanation: '"s" makes the /s/ sound as in sun, snake, and sit.',
      },
      {
        id: 'q-hl-2',
        question: 'When we blend /s/ + /u/ + /n/, what word does it make?',
        options: ['sun', 'sat', 'sam', 'son'],
        correctIndex: 0,
        explanation: 's-u-n blends to make the word "sun"!',
      },
      {
        id: 'q-hl-3',
        question: 'Which of these is a rhyming word for "cat"?',
        options: ['mat', 'dog', 'cup', 'bed'],
        correctIndex: 0,
        explanation: 'Cat and mat both end in the "-at" sound family.',
      },
    ],
  },
  {
    id: 'les-fal-r3-reading',
    gradeBand: 'Grade R-3',
    gradeLevel: 'Grade 2',
    subjectId: 'r3-fal',
    subjectName: 'FAL English',
    title: 'Digraphs (sh, ch, th) & Fluent Reading Aloud',
    topic: 'Foundation Phase - First Additional Language Reading',
    order: 1,
    isFree: true,
    durationMinutes: 12,
    capsObjective: 'Recognize consonant digraphs (sh, ch, th, wh) and read short South African narrative paragraphs with comprehension and expression.',
    summaryNotes: [
      'A digraph is two letters that work together to make one single sound.',
      's + h = /sh/ (quiet baby sound, as in "ship" or "fish").',
      'c + h = /ch/ (train sound, as in "chin" or "chop").',
      't + h = /th/ (tongue between teeth, as in "Thandi" or "three").',
      'When reading aloud, stop at full stops (.) to take a breath.',
    ],
    keyTerms: [
      { term: 'Digraph', definition: 'Two letters standing together to create one sound (sh, ch, th).' },
      { term: 'Fluency', definition: 'Reading words accurately, smoothly, and with natural rhythm.' },
    ],
    practicalExample: {
      scenario: 'Read this sentence with expression: "Thandi and Sipho visited the Kruger Park."',
      stepByStepSolution: [
        'Step 1: Notice the "Th" in Thandi - put your tongue gently between your teeth for /th/.',
        'Step 2: Notice the "ph" in Sipho - "ph" makes the /f/ sound like "phone".',
        'Step 3: Read smoothly without stopping in the middle of words.',
        'Step 4: Stop at the full stop to breathe!',
      ],
      examTip: 'Read like you are telling a fun bedtime story to a friend!',
    },
    video: {
      title: 'Foundation Phase English FAL: Learning Digraphs with Stories',
      duration: '4:20',
      thumbnailUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
      videoUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
    },
    quiz: [
      {
        id: 'q-fal-1',
        question: 'Which sound do "s" and "h" make when they stand together?',
        options: ['/sh/ as in ship', '/ch/ as in chair', '/th/ as in thumb', '/wh/ as in wheel'],
        correctIndex: 0,
        explanation: 's and h make the /sh/ sound as in ship and shop.',
      },
      {
        id: 'q-fal-2',
        question: 'In South African names, how is "ph" pronounced in "Sipho"?',
        options: ['/f/ sound like "phone"', '/p/ sound', '/h/ sound', '/b/ sound'],
        correctIndex: 0,
        explanation: '"ph" makes the /f/ sound, so Sipho is pronounced "See-fo".',
      },
    ],
  },
];

export const INITIAL_STUDY_GROUPS: StudyGroup[] = [
  {
    id: 'grp-matric-maths',
    name: 'Gauteng Matric Maths Masters',
    gradeBand: 'Grade 10-12' as GradeBand,
    grade: 'Grade 12',
    subjectId: '1012-math',
    subjectName: 'Mathematics',
    description: 'Aiming for 80%+ in Paper 1 & 2! Daily NSC past paper breakdown, calculus tips, and circle proofs.',
    maxMembers: 60,
    members: [
      {
        id: 'mem-1',
        fullName: 'Lindiwe Khumalo',
        grade: 'Grade 12',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        completedLessonsCount: 14,
        progressPercent: 88,
        badges: [INITIAL_BADGES[0], INITIAL_BADGES[1], INITIAL_BADGES[2]],
      },
      {
        id: 'mem-2',
        fullName: 'Sipho Ndlovu',
        grade: 'Grade 12',
        avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
        completedLessonsCount: 11,
        progressPercent: 72,
        badges: [INITIAL_BADGES[0], INITIAL_BADGES[3]],
      },
      {
        id: 'mem-3',
        fullName: 'Anathi Mthembu',
        grade: 'Grade 12',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        completedLessonsCount: 9,
        progressPercent: 60,
        badges: [INITIAL_BADGES[0]],
      },
      {
        id: 'mem-4',
        fullName: 'Tshepo Molefe',
        grade: 'Grade 12',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        completedLessonsCount: 12,
        progressPercent: 78,
        badges: [INITIAL_BADGES[0], INITIAL_BADGES[1]],
      },
    ],
    messages: [
      {
        id: 'msg-1',
        groupId: 'grp-matric-maths',
        userId: 'mem-1',
        userName: 'Lindiwe Khumalo',
        userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        text: 'Sanibonani squad! I am sharing the official 2024 NSC Maths Paper 1 PDF so we can study Question 1 together before tomorrow.',
        timestamp: '11:42 AM',
        status: 'read',
        attachment: {
          type: 'pdf',
          title: '2024 NSC November Mathematics Paper 1.pdf',
          fileSize: '1.4 MB',
          paperId: 'nsc-2024-math-p1',
          grade: 'Grade 12',
          subject: 'Mathematics',
          year: 2024,
          pageCount: 14,
          description: 'Official DBE CAPS Exam covering Algebra, Equations, Number Patterns & Calculus.',
        },
      },
      {
        id: 'msg-2',
        groupId: 'grp-matric-maths',
        userId: 'mem-2',
        userName: 'Sipho Ndlovu',
        userAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
        text: 'Thanks Lindiwe! Look at this scan from Question 1.1.3 on surd equations (2x - 5√x - 3 = 0). Can @Ms Elevate solve and break down the k-substitution method for us?',
        timestamp: '11:45 AM',
        status: 'read',
        attachment: {
          type: 'scan',
          title: 'Question 1.1.3 Surd Equation Worksheet Scan',
          dataUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
          grade: 'Grade 12',
          subject: 'Mathematics',
        },
      },
      {
        id: 'msg-3',
        groupId: 'grp-matric-maths',
        userId: 'ms-elevate-ai',
        userName: 'Ms Elevate (CAPS AI Tutor)',
        userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
        text: 'Sawubona squad! I scanned your uploaded problem: 2x - 5√x - 3 = 0. Here is the verified DBE step-by-step working so everyone secures full marks:',
        timestamp: '11:46 AM',
        isTeacher: true,
        isAi: true,
        status: 'read',
        attachment: {
          type: 'scan',
          title: 'Surd Quadratic Resolution (k-substitution)',
          aiSolution: {
            summary: 'Surd Quadratic Equation via k-substitution (Question 1.1.3)',
            subjectFormula: 'Let k = √x (where k ≥ 0)  ⇒  2k² - 5k - 3 = 0',
            stepByStep: [
              'Step 1: Notice that x = (√x)². Substitute k = √x to form a standard quadratic equation: 2k² - 5k - 3 = 0.',
              'Step 2: Factorise the quadratic expression: (2k + 1)(k - 3) = 0.',
              'Step 3: Solve for k: 2k + 1 = 0 ⇒ k = -1/2  OR  k - 3 = 0 ⇒ k = 3.',
              'Step 4: Check validity! In real numbers, √x cannot be negative, so reject k = -1/2.',
              'Step 5: Substitute back with valid k: √x = 3. Square both sides: (√x)² = 3²  ⇒  x = 9.',
            ],
            finalAnswer: 'x = 9 (k = -1/2 has no real solution)',
            capsTip: 'DBE Mark Allocation: 1 mark for standard form, 1 mark for factors, 1 mark for selecting positive k, and 1 mark for final answer x = 9. Always reject negative surd roots!',
            solvedAt: '11:46 AM',
          },
        },
      },
      {
        id: 'msg-4',
        groupId: 'grp-matric-maths',
        userId: 'mem-4',
        userName: 'Tshepo Molefe',
        userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        text: 'Yoh that makes so much sense now! I used to square the whole equation directly and get messy x² terms. Squad let\'s test ourselves on Question 1.2 next! 🔥',
        timestamp: '11:49 AM',
        status: 'read',
        reactions: { '🔥': 4, '💡': 3, '❤️': 2 },
      },
    ],
    createdAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'grp-phys-chem',
    name: 'KZN Physical Sciences Squad',
    gradeBand: 'Grade 10-12' as GradeBand,
    grade: 'Grade 12',
    subjectId: '1012-phys',
    subjectName: 'Physical Sciences',
    description: 'Focusing on Newton laws, electrodynamics, and organic esterification equations.',
    maxMembers: 60,
    members: [
      {
        id: 'mem-5',
        fullName: 'Keletso Dlamini',
        grade: 'Grade 12',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        completedLessonsCount: 8,
        progressPercent: 55,
        badges: [INITIAL_BADGES[0]],
      },
      {
        id: 'mem-6',
        fullName: 'Bontle Sithole',
        grade: 'Grade 12',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        completedLessonsCount: 13,
        progressPercent: 82,
        badges: [INITIAL_BADGES[0], INITIAL_BADGES[1]],
      },
    ],
    messages: [
      {
        id: 'msg-p1',
        groupId: 'grp-phys-chem',
        userId: 'mem-6',
        userName: 'Bontle Sithole',
        userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        text: 'Tip for tomorrow\'s physics test: always check whether the surface is frictionless before calculating net force!',
        timestamp: '09:15 AM',
      },
    ],
    createdAt: '2026-08-25T00:00:00Z',
  },
  {
    id: 'grp-ems-grade9',
    name: 'Soweto EMS & Accounting Stars',
    gradeBand: 'Grade 7-9' as GradeBand,
    grade: 'Grade 9',
    subjectId: '79-ems',
    subjectName: 'EMS',
    description: 'Senior Phase champions mastering journals, ledgers, and economic circular flow.',
    maxMembers: 60,
    members: [
      {
        id: 'mem-7',
        fullName: 'Mpho Modise',
        grade: 'Grade 9',
        avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
        completedLessonsCount: 6,
        progressPercent: 65,
        badges: [INITIAL_BADGES[0]],
      },
    ],
    messages: [
      {
        id: 'msg-e1',
        groupId: 'grp-ems-grade9',
        userId: 'mem-7',
        userName: 'Mpho Modise',
        userAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
        text: 'Who has completed the trial balance exercise for Lesson 1?',
        timestamp: '02:30 PM',
      },
    ],
    createdAt: '2026-09-02T00:00:00Z',
  },
];
