import { PastPaper } from '../types';

export const PAST_PAPERS: PastPaper[] = [
  {
    id: 'nsc-2024-math-p1',
    title: '2024 NSC November Mathematics Paper 1',
    subject: 'Mathematics',
    grade: 'Grade 12',
    year: 2024,
    session: 'November NSC',
    examBoard: 'DBE CAPS',
    paperNumber: 1,
    durationHours: 3,
    totalMarks: 150,
    description: 'National Senior Certificate Paper 1 covering Algebra, Equations & Inequalities, Number Patterns, Functions, Financial Mathematics, Differential Calculus, and Probability.',
    instructions: [
      'This question paper consists of 11 questions. Answer ALL questions.',
      'Clearly show ALL calculations, diagrams, graphs, etc. that you have used in determining your answers.',
      'Answers only will not necessarily be awarded full marks.',
      'An approved scientific calculator (non-programmable and non-graphical) may be used, unless stated otherwise.',
      'If necessary, round off answers to TWO decimal places, unless stated otherwise.',
      'Number the answers correctly according to the numbering system used in this question paper.',
    ],
    formulaSheetSummary: [
      'Quadratic Formula: x = [-b ± √(b² - 4ac)] / (2a)',
      'Compound Interest: A = P(1 + i)ⁿ',
      'Present Value Annuity: P = x[1 - (1 + i)⁻ⁿ] / i',
      'Future Value Annuity: F = x[(1 + i)ⁿ - 1] / i',
      'Calculus from 1st Principles: f\'(x) = lim(h→0) [f(x + h) - f(x)] / h',
    ],
    questions: [
      {
        number: 'Question 1',
        topic: 'Algebra, Equations & Inequalities',
        marks: 24,
        instructions: 'Solve for x in each of the following algebraic expressions:',
        subQuestions: [
          {
            label: '1.1.1',
            questionText: 'Solve for x: x² - 2x - 15 = 0',
            marks: 3,
            answerGuide: '(x - 5)(x + 3) = 0 ✓ [Factorisation - M1]\nx = 5 or x = -3 ✓ [Both critical values correct - A2]',
            examTip: 'Never divide across by x. Always bring terms to standard form ax² + bx + c = 0 before factoring.',
          },
          {
            label: '1.1.2',
            questionText: 'Solve for x: 3x² - 5x - 1 = 0 (correct to TWO decimal places)',
            marks: 4,
            answerGuide: 'Using quadratic formula: a = 3, b = -5, c = -1\nx = [-(-5) ± √((-5)² - 4(3)(-1))] / [2(3)] ✓ [Correct substitution into formula - M1]\nx = [5 ± √(25 + 12)] / 6 = [5 ± √37] / 6 ✓ [Simplification under surd - A1]\nx ≈ 1.85 or x ≈ -0.18 ✓ [Both decimal solutions rounded correctly - A2]',
            examTip: 'Remember to show the substituted formula before writing the calculator decimal answer to guarantee method marks.',
          },
          {
            label: '1.1.3',
            questionText: 'Solve for x: 2x - 5√x - 3 = 0',
            marks: 4,
            answerGuide: 'Let k = √x where k ≥ 0\n2k² - 5k - 3 = 0 ✓ [Standard form substitution - M1]\n(2k + 1)(k - 3) = 0 ✓ [Factorisation - M1]\nk = -1/2 (no real solution since √x ≥ 0) or k = 3 ✓ [Selection of valid k - A1]\n√x = 3 ⇒ x = 9 ✓ [Squaring both sides - A1]',
            examTip: 'Always check solutions in surd equations. √x cannot produce a negative value in real numbers.',
          },
          {
            label: '1.2',
            questionText: 'Solve simultaneously for x and y:\n  x - y = 3\n  x² + xy - 2y² = 0',
            marks: 6,
            answerGuide: 'From (1): x = y + 3 ✓ [Make x subject - M1]\nSubstitute into (2): (y + 3)² + (y + 3)y - 2y² = 0\n(y² + 6y + 9) + (y² + 3y) - 2y² = 0 ✓ [Expansion - M1]\n9y + 9 = 0 ⇒ 9y = -9 ⇒ y = -1 ✓ [Value of y - A1]\nSubstitute back: x = (-1) + 3 = 2 ✓ [Value of x - A1]\nVerification in x² + xy - 2y² = (2)² + (2)(-1) - 2(-1)² = 4 - 2 - 2 = 0 ✓ [Complete solution - A2]',
            examTip: 'Double check whether the quadratic factors before substituting; here x² + xy - 2y² = (x + 2y)(x - y) provides an alternative quick route.',
          },
          {
            label: '1.3',
            questionText: 'Given f(x) = √(2x - 7). For which values of x is f(x) a real number?',
            marks: 3,
            answerGuide: 'For f(x) to be real, the radicand must be non-negative:\n2x - 7 ≥ 0 ✓ [Condition for real surd - M1]\n2x ≥ 7\nx ≥ 7/2 or x ≥ 3.5 ✓ [Inequality solution - A2]',
            examTip: 'Real roots requires ≥ 0. If question asks for non-zero real denominator, use > 0 strictly.',
          },
        ],
      },
      {
        number: 'Question 2',
        topic: 'Number Sequences & Sigma Notation',
        marks: 15,
        instructions: 'Answer the questions on geometric and arithmetic sequences:',
        subQuestions: [
          {
            label: '2.1.1',
            questionText: 'Given the geometric sequence: 3 ; 6 ; 12 ; 24 ; ... Determine the 10th term (T₁₀).',
            marks: 2,
            answerGuide: 'First term a = 3, common ratio r = 6/3 = 2 ✓ [Identification of a and r - A1]\nT₁₀ = a·r⁹ = 3 · (2)⁹ = 3 · 512 = 1 536 ✓ [Calculation of T₁₀ - A1]',
            examTip: 'Always write down the formula Tₙ = arⁿ⁻¹ before computing powers.',
          },
          {
            label: '2.1.2',
            questionText: 'Evaluate the sum: ∑(k=1 to 8) [ 3 · 2ᵏ⁻¹ ]',
            marks: 3,
            answerGuide: 'Geometric series with a = 3, r = 2, n = 8 terms ✓ [Parameters identified - A1]\nSₙ = a(rⁿ - 1) / (r - 1)\nS₈ = 3(2⁸ - 1) / (2 - 1) = 3(256 - 1) / 1 ✓ [Substitution - M1]\nS₈ = 3(255) = 765 ✓ [Final answer - A1]',
            examTip: 'Verify number of terms: top index - bottom index + 1 = 8 - 1 + 1 = 8 terms.',
          },
          {
            label: '2.2',
            questionText: 'For which values of x will the infinite geometric series converges:\n  (2x - 1) + (2x - 1)² + (2x - 1)³ + ...',
            marks: 4,
            answerGuide: 'Common ratio r = (2x - 1)\nFor convergence: -1 < r < 1 ✓ [Condition for sum to infinity - M1]\n-1 < 2x - 1 < 1\nAdd 1 to all sides: 0 < 2x < 2 ✓ [Inequality manipulation - M1]\nDivide by 2: 0 < x < 1 ✓ [Interval for convergence - A2]',
            examTip: 'A geometric series converges strictly when -1 < r < 1. Never include ≤ or ≥.',
          },
        ],
      },
      {
        number: 'Question 3',
        topic: 'Differential Calculus & First Principles',
        marks: 20,
        instructions: 'Determine derivatives and tangent equations using standard CAPS rules:',
        subQuestions: [
          {
            label: '3.1',
            questionText: 'Determine f\'(x) from FIRST PRINCIPLES if f(x) = 3x² - 4x.',
            marks: 5,
            answerGuide: 'f(x + h) = 3(x + h)² - 4(x + h) = 3(x² + 2xh + h²) - 4x - 4h = 3x² + 6xh + 3h² - 4x - 4h ✓ [f(x+h) expanded - M1]\nf(x + h) - f(x) = (3x² + 6xh + 3h² - 4x - 4h) - (3x² - 4x) = 6xh + 3h² - 4h ✓ [Subtraction - A1]\nf\'(x) = lim(h→0) [h(6x + 3h - 4)] / h ✓ [Factoring h and dividing out - M1]\nf\'(x) = lim(h→0) (6x + 3h - 4) = 6x - 4 ✓ [Taking limit h→0 - A2]',
            examTip: 'Keep writing lim(h→0) in every step until you actually substitute h = 0 in the final line. Omitting lim results in deduction of 1 mark.',
          },
          {
            label: '3.2',
            questionText: 'Determine dy/dx if y = 4√x - 5/x³.',
            marks: 4,
            answerGuide: 'Rewrite with fractional and negative exponents first:\ny = 4x^(1/2) - 5x⁻³ ✓ [Exponential form - M1]\ndy/dx = 4(1/2)x^(-1/2) - 5(-3)x⁻⁴ ✓ [Applying power rule - M1]\ndy/dx = 2x^(-1/2) + 15x⁻⁴ = 2/√x + 15/x⁴ ✓ [Simplified derivative - A2]',
            examTip: 'Never differentiate while a variable remains in the denominator or under a radical surd.',
          },
          {
            label: '3.3',
            questionText: 'The cubic function g(x) = -x³ + bx² + cx + d has turning points at x = -1 and x = 3. Determine the x-coordinate of the point of inflection.',
            marks: 4,
            answerGuide: 'Method 1: Point of inflection of a cubic function occurs at the midpoint of turning points x = (x₁ + x₂) / 2\nx = (-1 + 3) / 2 = 2/2 = 1 ✓ [Inflection coordinate formula - A2]\nMethod 2: g\'\'(x) = 0. g\'(x) has roots at -1 and 3 ⇒ g\'(x) = -3(x + 1)(x - 3) = -3(x² - 2x - 3) = -3x² + 6x + 9 ✓ [Derivative function - M1]\ng\'\'(x) = -6x + 6 = 0 ⇒ 6x = 6 ⇒ x = 1 ✓ [Inflection point - A1]',
            examTip: 'For any cubic polynomial, the point of inflection is the exact arithmetic mean of the two local extrema.',
          },
        ],
      },
    ],
    memoNotes: [
      'Question 1.1: Standard factoring produces instant full marks without quadratic formula.',
      'Question 3.1: Candidates who drop "lim h->0" before the last step lose 1 notation mark per national grading guideline.',
      'Total Paper 1 marks: 150. Time allocation: 1.2 minutes per mark.',
    ],
  },
  {
    id: 'nsc-2024-math-p2',
    title: '2024 NSC November Mathematics Paper 2',
    subject: 'Mathematics',
    grade: 'Grade 12',
    year: 2024,
    session: 'November NSC',
    examBoard: 'DBE CAPS',
    paperNumber: 2,
    durationHours: 3,
    totalMarks: 150,
    description: 'National Senior Certificate Paper 2 covering Statistics, Analytical Geometry (Lines & Circles), Trigonometry (Identities, Reduction, General Solution), and Euclidean Geometry Circle Theorems.',
    instructions: [
      'This question paper consists of 10 questions. Answer ALL questions.',
      'Clearly show all calculations, diagrams, and geometric REASONS.',
      'REASONS must be stated in standard CAPS abbreviations [e.g. ∠ in semi-circle, tan-chord thm].',
      'If necessary, round off answers to TWO decimal places.',
    ],
    formulaSheetSummary: [
      'Distance formula: d = √[(x₂ - x₁)² + (y₂ - y₁)²]',
      'Midpoint: M((x₁ + x₂)/2, (y₁ + y₂)/2)',
      'Circle equation: (x - a)² + (y - b)² = r²',
      'Tangent to Circle: radius ⊥ tangent at point of contact',
      'Trigonometry Cosine Rule: a² = b² + c² - 2bc·cos(A)',
      'Sine Rule: a/sin(A) = b/sin(B)',
    ],
    questions: [
      {
        number: 'Question 1',
        topic: 'Analytical Geometry - Circles & Tangents',
        marks: 21,
        instructions: 'In the Cartesian plane, the circle with center M(2 ; -3) passes through the point P(6 ; 1).',
        subQuestions: [
          {
            label: '1.1',
            questionText: 'Determine the radius r of the circle, and hence write down the equation of the circle in the form (x - a)² + (y - b)² = r².',
            marks: 4,
            answerGuide: 'r² = (x_P - x_M)² + (y_P - y_M)²\nr² = (6 - 2)² + (1 - (-3))² = (4)² + (4)² = 16 + 16 = 32 ✓ [Distance formula substitution - M1]\nRadius r = √32 = 4√2 ✓ [Radius value - A1]\nCircle equation: (x - 2)² + (y + 3)² = 32 ✓ [Circle standard form - A2]',
            examTip: 'Leave r² as 32 in the standard equation; do not write (4√2)².',
          },
          {
            label: '1.2',
            questionText: 'Determine the gradient of the radius MP, and hence deduce the equation of the tangent line to the circle at point P(6 ; 1).',
            marks: 5,
            answerGuide: 'm_MP = (y₂ - y₁) / (x₂ - x₁) = (1 - (-3)) / (6 - 2) = 4/4 = 1 ✓ [Gradient of radius - A1]\nTangent is perpendicular to radius: m_tan · m_MP = -1 [radius ⊥ tangent] ✓ [Reason and property - M1]\nm_tan = -1\nEquation: y - y₁ = m(x - x₁)\ny - 1 = -1(x - 6) ⇒ y - 1 = -x + 6 ✓ [Substitution of point P - M1]\ny = -x + 7 ✓ [Final tangent equation - A2]',
            examTip: 'Always write the reason [radius ⊥ tangent] in brackets next to your perpendicular gradient calculation to earn the geometric method mark.',
          },
        ],
      },
      {
        number: 'Question 2',
        topic: 'Euclidean Geometry - Circle Theorems',
        marks: 18,
        instructions: 'In the figure, O is the center of circle ABCD. Chord AB is parallel to chord CD. AB subtends ∠AOB at center O.',
        subQuestions: [
          {
            label: '2.1',
            questionText: 'Prove the theorem which states that the angle subtended by an arc at the center of a circle is double the size of the angle subtended by the same arc at any point on the circumference.',
            marks: 6,
            answerGuide: 'Construction: Draw diameter through P and center O, extend to E. ✓ [Construction line - M1]\nIn ΔOAP: OA = OP [radii] ⇒ ∠OAP = ∠OPA = x [∠s opp equal sides] ✓ [Base angles - A1]\nExterior ∠AOE = ∠OAP + ∠OPA = 2x [ext ∠ of Δ] ✓ [Exterior angle theorem - A1]\nSimilarly in ΔOBP: OB = OP [radii] ⇒ ∠OBP = ∠OPB = y\nExterior ∠BOE = 2y [ext ∠ of Δ] ✓ [Second angle - A1]\n∠AOB = ∠AOE + ∠BOE = 2x + 2y = 2(x + y) = 2 · ∠APB ✓ [Conclusion - A2]',
            examTip: 'One of the 6 examinable Euclidean proofs is GUARANTEED to be in Paper 2 for 5 to 6 marks. Memorize all six standard proofs!',
          },
        ],
      },
    ],
    memoNotes: [
      'Always check that geometric reasons use accepted CAPS abbreviations.',
      'Paper 2 Euclidean Geometry carries 50 marks out of 150; mastery of circle theorems guarantees an easy distinction.',
    ],
  },
  {
    id: 'nsc-2023-phys-p1',
    title: '2023 NSC November Physical Sciences Paper 1 (Physics)',
    subject: 'Physical Sciences',
    grade: 'Grade 12',
    year: 2023,
    session: 'November NSC',
    examBoard: 'DBE CAPS',
    paperNumber: 1,
    durationHours: 3,
    totalMarks: 150,
    description: 'National Senior Certificate Physical Sciences Paper 1 covering Momentum & Impulse, Newton\'s Laws of Motion, Work-Energy-Power, Doppler Effect, and Electrodynamics.',
    instructions: [
      'Write your answers in your answer book.',
      'Start each question on a NEW page in the answer book.',
      'Number the answers correctly according to the numbering system used in this question paper.',
      'Leave ONE line between two subquestions, e.g. between QUESTION 2.1 and QUESTION 2.2.',
      'You may use a non-programmable calculator.',
      'Round off your final numerical answers to a minimum of TWO decimal places.',
    ],
    formulaSheetSummary: [
      'Newton II: F_net = m·a',
      'Weight: F_g = m·g (where g = 9.8 m·s⁻²)',
      'Frictional force: f_k = μ_k · N',
      'Work: W = F · Δx · cos(θ)',
      'Work-Energy Theorem: W_net = ΔE_k = (1/2)m(v_f² - v_i²)',
      'Doppler Effect: f_L = [(v ± v_L) / (v ∓ v_s)] · f_s',
    ],
    questions: [
      {
        number: 'Question 1',
        topic: 'Newton\'s Laws on Inclined Planes & Friction',
        marks: 19,
        instructions: 'A 5 kg block is held at rest on a rough inclined plane making an angle of 30° with the horizontal. A constant tension force T = 45 N acts parallel up the incline.',
        subQuestions: [
          {
            label: '1.1',
            questionText: 'State Newton\'s Second Law of Motion in words.',
            marks: 2,
            answerGuide: 'When a net resultant force acts on an object, the object accelerates in the direction of the net force with an acceleration directly proportional to the force and inversely proportional to the mass of the object. ✓✓ [2 marks for full definition, 0 if "resultant / net" is omitted]',
            examTip: 'Never leave out the word "net" or "resultant". In NSC physics, writing "force" instead of "net force" loses both marks!',
          },
          {
            label: '1.2',
            questionText: 'Draw a fully labeled free-body diagram showing all the forces acting on the 5 kg block as it moves up the incline.',
            marks: 4,
            answerGuide: 'Forces required:\n• Applied Tension T (up incline) ✓\n• Normal force F_N / N (perpendicular to surface) ✓\n• Gravitational force F_g / w (vertically downwards) ✓\n• Kinetic friction f_k (down the incline, opposite to motion) ✓',
            examTip: 'Arrows must touch the dot in a free body diagram. Never draw components (F_gx, F_gy) on a free body diagram unless explicitly asked; draw full F_g vertically down.',
          },
          {
            label: '1.3',
            questionText: 'Given the coefficient of kinetic friction μ_k = 0.25, calculate the magnitude of the kinetic frictional force f_k.',
            marks: 3,
            answerGuide: 'F_N = m·g·cos(30°) = 5 · (9.8) · cos(30°) = 49 · 0.8660 = 42.44 N ✓ [Normal force calculation - M1]\nf_k = μ_k · F_N = 0.25 · 42.44 N = 10.61 N ✓ [Friction equation & substitution - A2]',
            examTip: 'On an incline, F_N = mg·cos(θ), NOT mg.',
          },
          {
            label: '1.4',
            questionText: 'Calculate the acceleration of the block up the incline.',
            marks: 5,
            answerGuide: 'F_gx = m·g·sin(30°) = 5 · 9.8 · 0.5 = 24.5 N down the incline ✓ [Parallel component of gravity - A1]\nF_net = T - F_gx - f_k = 45 - 24.5 - 10.61 = 9.89 N up incline ✓ [Net force equation - M1]\nF_net = m·a\n9.89 = 5 · a ⇒ a = 9.89 / 5 = 1.98 m·s⁻² up the incline ✓✓ [Numerical answer with unit and direction - A2]',
            examTip: 'Acceleration is a vector quantity; always state magnitude, correct unit (m·s⁻²), and direction (up the incline).',
          },
        ],
      },
      {
        number: 'Question 2',
        topic: 'Doppler Effect with Sound Waves',
        marks: 12,
        instructions: 'An ambulance siren emits sound of frequency 650 Hz while travelling at 25 m·s⁻¹ towards a stationary listener. Take speed of sound in air as 340 m·s⁻¹.',
        subQuestions: [
          {
            label: '2.1',
            questionText: 'Name the wave phenomenon that explains the observed change in frequency of sound.',
            marks: 1,
            answerGuide: 'Doppler Effect ✓ [1 mark]',
          },
          {
            label: '2.2',
            questionText: 'Calculate the frequency of the sound detected by the stationary listener as the ambulance approaches.',
            marks: 4,
            answerGuide: 'Formula: f_L = [v / (v - v_s)] · f_s ✓ [Standard formula - M1]\nv_L = 0 (stationary listener), ambulance approaches ⇒ minus sign in denominator\nf_L = [340 / (340 - 25)] · 650 ✓ [Correct substitutions - M1]\nf_L = [340 / 315] · 650 = 1.07936 · 650 = 701.59 Hz ✓ [Answer with unit Hz - A2]',
            examTip: 'When source approaches listener, frequency MUST increase (701.59 > 650 Hz). If your answer is smaller, you used the wrong sign!',
          },
        ],
      },
    ],
    memoNotes: [
      'F_net = ma formula mark is only awarded if formula is written as on data sheet.',
      'Always deduct 1 mark for missing or incorrect units on final numerical answers.',
    ],
  },
  {
    id: 'nsc-2023-chem-p2',
    title: '2023 NSC November Physical Sciences Paper 2 (Chemistry)',
    subject: 'Physical Sciences',
    grade: 'Grade 12',
    year: 2023,
    session: 'November NSC',
    examBoard: 'DBE CAPS',
    paperNumber: 2,
    durationHours: 3,
    totalMarks: 150,
    description: 'National Senior Certificate Physical Sciences Paper 2 covering Organic Molecules (IUPAC naming, intermolecular forces), Rates of Reaction, Chemical Equilibrium (Kc), Acids & Bases, and Galvanic & Electrolytic Cells.',
    instructions: [
      'Answer all questions.',
      'Show the formulae and substitutions in all calculations.',
      'Round off your final numerical answers to a minimum of TWO decimal places.',
    ],
    formulaSheetSummary: [
      'Concentration: c = n / V = m / (M · V)',
      'Moles: n = m / M',
      'Equilibrium Constant: Kc = [Products]ᶜ / [Reactants]ʳ',
      'pH: pH = -log[H₃O⁺]',
      'Cell potential: E°_cell = E°_cathode - E°_anode',
    ],
    questions: [
      {
        number: 'Question 1',
        topic: 'Organic Nomenclature & Intermolecular Forces',
        marks: 18,
        instructions: 'Consider the following organic compounds: A: CH₃-CH(CH₃)-CH₂-OH ; B: CH₃-CH₂-CH₂-COOH ; C: CH₃-COO-CH₂-CH₃',
        subQuestions: [
          {
            label: '1.1',
            questionText: 'Write down the IUPAC name for Compound A.',
            marks: 3,
            answerGuide: 'Longest chain with -OH group has 3 carbons (propan-1-ol).\nMethyl branch on carbon 2: 2-methylpropan-1-ol ✓✓✓ [3 marks: "2-methyl" (1), "propan" (1), "1-ol" (1)]',
            examTip: 'Remember hyphens between numbers and letters: 2-methylpropan-1-ol, not 2 methyl propanol.',
          },
          {
            label: '1.2',
            questionText: 'Identify the homologous series to which Compound C belongs, and write down the name of the functional group.',
            marks: 2,
            answerGuide: 'Homologous series: Esters ✓\nFunctional group: Ester group / alkoxycarbonyl group [-COO-] ✓',
          },
          {
            label: '1.3',
            questionText: 'Explain why Compound B (butanoic acid) has a significantly higher boiling point than Compound C (ethyl ethanoate) of similar molecular mass.',
            marks: 5,
            answerGuide: '• Compound B has TWO sites for hydrogen bonding between molecules (forms stable dimers). ✓ [M1]\n• Compound C has dipole-dipole forces and London forces, but NO hydrogen bonding between its own molecules. ✓ [M1]\n• Hydrogen bonds are significantly stronger than dipole-dipole forces. ✓ [Comparison - A1]\n• More energy is required to overcome the stronger intermolecular forces in Compound B. ✓ [Energy factor - A1]\n• Therefore, Compound B has a higher boiling point. ✓ [Conclusion - A1]',
            examTip: 'The CAPS formula for explaining boiling points must ALWAYS name the types of intermolecular forces in BOTH compounds, compare strength, mention energy needed, and conclude on boiling point.',
          },
        ],
      },
    ],
    memoNotes: [
      'All 5 points must be mentioned in intermolecular force comparison to score full 5 marks.',
    ],
  },
  {
    id: 'nsc-2024-life-p1',
    title: '2024 June Exam Life Sciences Paper 1',
    subject: 'Life Sciences',
    grade: 'Grade 12',
    year: 2024,
    session: 'June Exam',
    examBoard: 'DBE CAPS',
    paperNumber: 1,
    durationHours: 2.5,
    totalMarks: 150,
    description: 'CAPS Life Sciences Paper 1 covering Meiosis, Reproduction in Vertebrates, Human Reproduction, Nervous System & Receptors (Eye & Ear), and Endocrine System.',
    instructions: [
      'Answer ALL the questions.',
      'Write all answers in the ANSWER BOOK.',
      'Start the answers to EACH question at the top of a NEW page.',
      'Number the answers correctly according to the numbering system used in this question paper.',
      'Present your answers according to the regulations of each question.',
      'Make ALL drawings in pencil and label them in blue or black ink.',
    ],
    questions: [
      {
        number: 'Question 1',
        topic: 'Meiosis, Crossing Over & Non-Disjunction',
        marks: 16,
        instructions: 'The diagram shows a cell in Phase 1 of Meiosis undergoing genetic exchange.',
        subQuestions: [
          {
            label: '1.1',
            questionText: 'Identify the phase of meiosis during which crossing over occurs, and state the significance of crossing over.',
            marks: 3,
            answerGuide: 'Phase: Prophase I ✓ [1 mark]\nSignificance: Introduces genetic variation / recombinant chromatids among offspring ✓✓ [2 marks]',
            examTip: 'Be specific: Prophase I, not just "Prophase". Roman numerals are required in meiosis phases.',
          },
          {
            label: '1.2',
            questionText: 'Explain what is meant by non-disjunction, and name ONE genetic condition that results from non-disjunction of chromosome 21.',
            marks: 4,
            answerGuide: 'Non-disjunction: The failure of homologous chromosome pairs (in Anaphase I) or sister chromatids (in Anaphase II) to separate properly during meiosis. ✓✓ [2 marks]\nCondition: Down Syndrome / Trisomy 21 ✓✓ [2 marks]',
          },
        ],
      },
    ],
    memoNotes: [
      'Label lines in biological diagrams must be straight and touch the structure without arrowheads.',
    ],
  },
];
